analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0.8727599
  lightness: 0
  brandColors:
    - '#1F160E'
    - '#166E9A'
    - '#915C01'
    - '#F2F2F2'
    - '#FFCF6E'
  rhythmicContrast: 0
typography_spectrum: 0.8440861
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2688172
favicon: null
name: arboladelante
