name: arboladelante
favicon: null
layout_spectrum: 0
typography_spectrum: 0.01672
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: personal work
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343434'
    - '#5e5556'
    - '#787880'
    - '#8b8585'
    - '#1a1d24'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
