title: personal work
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.953405
  lightness: 0.9856631
  brandStrength: 0.937276
  brandColors:
    - '#CF3938'
    - '#D8D6C8'
    - '#DF775E'
    - '#ACA58F'
    - '#4B5541'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: arboladelante
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4605735
layout_spectrum: 1
