name: arboladelante
favicon: null
layout_spectrum: 0.27432
typography_spectrum: 0.4605735
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: arboladelante
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#535454'
    - '#FCE876'
    - '#E1A289'
    - '#C5C8BC'
    - '#310D10'
  brandStrength: 0.937276
  lightness: 0.9856631
  saturation: 0.953405
  rhythmicContrast: 1
purpose: []
