name: arboladelante
favicon: null
layout_spectrum: 0.68378
typography_spectrum: 0.85246
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Arboladelante - Visual Laborer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4d4644'
    - '#827a75'
    - '#a19992'
    - '#d0c8c3'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
